# Qualcomm Snapdragon 675 (sm6150)

TARGET_PRODUCT_SHIPPING_API_LEVEL=28
TARGET_PLATFORM_SDK_VERSION=36
TARGET_BOARD_API_LEVEL=28

# Static partitions
TARGET_USE_DYNAMIC_PARTITIONS=false

# OS
TARGET_OS_SINGLE_SYSTEM_IMAGE="qssi"
TARGET_OS_FILE_SYSTEM_TYPE="erofs"
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false
